from handcalcs.parsing.ast_parser import AST_Parser
from handcalcs.parsing.sequence import HcSequence
from handcalcs.parsing.comment_parser import is_comment_command, split_commands, is_markdown_heading
from handcalcs.parsing.block_nodes import (
    IfBlock,
    ForBlock,
    ElifBlock,
    ElseBlock
)
from handcalcs.parsing.line_nodes import (
    CalcLine,
    ExprLine,
    CommentLine,
    MarkdownComment,
    Import,
)

from handcalcs.parsing.nodes import (
    List,
    Name,
    Constant,
)

from handcalcs.parsing.null_values import (
    NoValue,
    HcNotImplemented
)

from handcalcs.parsing.inline_nodes import (
    FunctionCall,
    ComprehensionChain,
    Comprehension,
    Compare,
)

from handcalcs.parsing.operator_nodes import (
    AddOp,
    SubOp,
    MultOp,
    DivOp,
    FloorOp,
    ModuloOp,
    PowOp,
    EqOp,
    NeqOp,
    GtOp,
    GtEOp,
    LtOp,
    LtEOp,
)
import math
import pytest
from collections import deque, ChainMap

import submodule_1 as sub1
import submodule_2 as sub2

@pytest.fixture
def basic_parser():
    parser = AST_Parser(globals(), global_exclusions=['collections', 'deque'])
    return parser

def test_calc_lines(basic_parser):
    source_1 = """a = d = 4"""
    source_2 = """b = (a + b * (2 + a/4)) / (3 * a)"""
    source_3 = """c = math.sin(b / a)**2 + math.cos(b / a)**2"""

    assert basic_parser(source_1) == deque([
            CalcLine(
                assigns=deque([
                    Name(
                        identifier='a'
                    ),
                    Name(
                        identifier='d'
                    )
                ]),
                expression_tree=deque([
                    Constant(
                        value=4
                    )
                ])
            )
        ])

    assert basic_parser(source_2) == deque([
                CalcLine(
                    assigns=deque([
                        Name(
                            identifier='b'
                        )
                    ]),
                    expression_tree=deque([
                        DivOp(
                            left=AddOp(
                                left=Name(
                                    identifier='a'
                                ),
                                right=MultOp(
                                    left=Name(
                                        identifier='b'
                                    ),
                                    right=AddOp(
                                        left=Constant(
                                            value=2
                                        ),
                                        right=DivOp(
                                            left=Name(
                                                identifier='a'
                                            ),
                                            right=Constant(
                                                value=4
                                            )
                                        )
                                    )
                                )
                            ),
                            right=MultOp(
                                left=Constant(
                                    value=3
                                ),
                                right=Name(
                                    identifier='a'
                                )
                            )
                        )
                    ])
                )
            ])

    assert basic_parser(source_3) == deque([
                CalcLine(
                    assigns=deque([
                        Name(
                            identifier='c'
                        )
                    ]),
                    expression_tree=deque([
                        AddOp(
                            left=PowOp(
                                left=FunctionCall(
                                    namespace=Name(
                                        identifier='math',
                                        value='math'
                                    ),
                                    function_name=Name(
                                        identifier='sin',
                                        value='sin'
                                    ),
                                    args=deque([
                                        DivOp(
                                            left=Name(
                                                identifier='b'
                                            ),
                                            right=Name(
                                                identifier='a'
                                            )
                                        )
                                    ])
                                ),
                                right=Constant(
                                    value=2
                                )
                            ),
                            right=PowOp(
                                left=FunctionCall(
                                    namespace=Name(
                                        identifier='math',
                                        value='math'
                                    ),
                                    function_name=Name(
                                        identifier='cos',
                                        value='cos'
                                    ),
                                    args=deque([
                                        DivOp(
                                            left=Name(
                                                identifier='b'
                                            ),
                                            right=Name(
                                                identifier='a'
                                            )
                                        )
                                    ])
                                ),
                                right=Constant(
                                    value=2
                                )
                            )
                        )
                    ])
                )
            ])


# def test_function_recursion(basic_parser):
#     source_1 = "a = sub1.my_calc(2, 3)"
#     ...  # (left commented out; predates the operator-node AST)


def test_if_blocks():
    # The if/elif/else evaluation needs `a` and `b` resolvable, so build a
    # parser whose context (locals, globals) is a ChainMap like HcSequence does.
    source_1 = """
a = 4
b = 5
if 2 <= a < 5:
    d = 4
    print(d)
elif a > b:
    d = 5
    print(d)
else:
    d = 6
    print(d)
"""
    basic_parser = AST_Parser(
        ChainMap({}, {"a": 4, "b": 5}), global_exclusions=['collections', 'deque']
    )
    assert basic_parser(source_1) == deque([
        CalcLine(
            assigns=deque([
                Name(
                    identifier='a',
                    value=4
                )
            ]),
            expression_tree=deque([
                Constant(
                    value=4
                )
            ])
        ),
        CalcLine(
            assigns=deque([
                Name(
                    identifier='b',
                    value=5
                )
            ]),
            expression_tree=deque([
                Constant(
                    value=5
                )
            ])
        ),
        IfBlock(
            lines=deque([
                CalcLine(
                    assigns=deque([
                        Name(
                            identifier='d'
                        )
                    ]),
                    expression_tree=deque([
                        Constant(
                            value=4
                        )
                    ])
                ),
                ExprLine(
                    expression_tree=deque([
                        FunctionCall(
                            namespace=Name(
                                identifier='__main__',
                                value='__main__'
                            ),
                            function_name=Name(
                                identifier='print',
                                value='print'
                            ),
                            args=deque([
                                Name(
                                    identifier='d'
                                )
                            ])
                        )
                    ])
                )
            ]),
            test=Compare(
                comparison=deque([
                    Constant(
                        value=2
                    ),
                    LtEOp,
                    Name(
                        identifier='a',
                        value=4
                    ),
                    LtOp,
                    Constant(
                        value=5
                    )
                ])
            ),
            orelse=deque([
                IfBlock(
                    lines=deque([
                        CalcLine(
                            assigns=deque([
                                Name(
                                    identifier='d'
                                )
                            ]),
                            expression_tree=deque([
                                Constant(
                                    value=5
                                )
                            ])
                        ),
                        ExprLine(
                            expression_tree=deque([
                                FunctionCall(
                                    namespace=Name(
                                        identifier='__main__',
                                        value='__main__'
                                    ),
                                    function_name=Name(
                                        identifier='print',
                                        value='print'
                                    ),
                                    args=deque([
                                        Name(
                                            identifier='d'
                                        )
                                    ])
                                )
                            ])
                        )
                    ]),
                    test=Compare(
                        comparison=deque([
                            Name(
                                identifier='a',
                                value=4
                            ),
                            GtOp,
                            Name(
                                identifier='b',
                                value=5
                            )
                        ])
                    ),
                    orelse=deque([
                        CalcLine(
                            assigns=deque([
                                Name(
                                    identifier='d'
                                )
                            ]),
                            expression_tree=deque([
                                Constant(
                                    value=6
                                )
                            ])
                        ),
                        ExprLine(
                            expression_tree=deque([
                                FunctionCall(
                                    namespace=Name(
                                        identifier='__main__',
                                        value='__main__'
                                    ),
                                    function_name=Name(
                                        identifier='print',
                                        value='print'
                                    ),
                                    args=deque([
                                        Name(
                                            identifier='d'
                                        )
                                    ])
                                )
                            ])
                        )
                    ]),
                    is_true=False
                )
            ]),
            is_true=True
        )
    ])


def test_for_blocks():
    source_1 = """import math
a = [0, 1, 2, 3, 4, 5]
b = 6
acc = []
for elem in a:
    value = elem + b
    acc.append(value)
"""
    source_2 = """
a = [0, 1, 2, 3, 4, 5]
b = 6
values = [elem + b for elem in a]
"""
    source_1_locals = {}
    exec(source_1, locals=source_1_locals)
    basic_parser = AST_Parser(globals() | source_1_locals, global_exclusions=['collections', 'deque'])
    assert basic_parser(source_1) == deque([
        Import(
            names=deque([
                Name(
                    identifier='math',
                    value=None
                )
            ])
        ),
        CalcLine(
            assigns=deque([
                Name(
                    identifier='a',
                    value=[
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                )
            ]),
            expression_tree=deque([
                List(
                    elems=deque([
                        Constant(
                            value=0
                        ),
                        Constant(
                            value=1
                        ),
                        Constant(
                            value=2
                        ),
                        Constant(
                            value=3
                        ),
                        Constant(
                            value=4
                        ),
                        Constant(
                            value=5
                        )
                    ])
                )
            ])
        ),
        CalcLine(
            assigns=deque([
                Name(
                    identifier='b',
                    value=6
                )
            ]),
            expression_tree=deque([
                Constant(
                    value=6
                )
            ])
        ),
        CalcLine(
            assigns=deque([
                Name(
                    identifier='acc',
                    value=[
                        6,
                        7,
                        8,
                        9,
                        10,
                        11
                    ]
                )
            ]),
            expression_tree=deque([
                List(
                    elems=deque([])
                )
            ])
        ),
        ForBlock(
            lines=deque([
                CalcLine(
                    assigns=deque([
                        Name(
                            identifier='value',
                            value=11
                        )
                    ]),
                    expression_tree=deque([
                        AddOp(
                            left=Name(
                                identifier='elem',
                                value=5
                            ),
                            right=Name(
                                identifier='b',
                                value=6
                            )
                        )
                    ])
                ),
                ExprLine(
                    expression_tree=deque([
                        FunctionCall(
                            namespace=Name(
                                identifier='acc',
                                value='acc'
                            ),
                            function_name=Name(
                                identifier='append',
                                value='append'
                            ),
                            args=deque([
                                Name(
                                    identifier='value',
                                    value=11
                                )
                            ])
                        )
                    ])
                )
            ]),
            assigns=deque([
                Name(
                    identifier='elem',
                    value=5
                )
            ]),
            iterator=deque([
                Name(
                    identifier='a',
                    value=[
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                )
            ])
        )
    ])

    source_2_locals = {}
    exec(source_2, locals=source_2_locals)
    basic_parser = AST_Parser(globals() | source_2_locals, global_exclusions=['collections', 'deque'])
    assert basic_parser(source_2) == deque([
        CalcLine(
            assigns=deque([
                Name(
                    identifier='a',
                    value=[
                        0,
                        1,
                        2,
                        3,
                        4,
                        5
                    ]
                )
            ]),
            expression_tree=deque([
                List(
                    elems=deque([
                        Constant(
                            value=0
                        ),
                        Constant(
                            value=1
                        ),
                        Constant(
                            value=2
                        ),
                        Constant(
                            value=3
                        ),
                        Constant(
                            value=4
                        ),
                        Constant(
                            value=5
                        )
                    ])
                )
            ])
        ),
        CalcLine(
            assigns=deque([
                Name(
                    identifier='b',
                    value=6
                )
            ]),
            expression_tree=deque([
                Constant(
                    value=6
                )
            ])
        ),
        CalcLine(
            assigns=deque([
                Name(
                    identifier='values',
                    value=[
                        6,
                        7,
                        8,
                        9,
                        10,
                        11
                    ]
                )
            ]),
            expression_tree=deque([
                ComprehensionChain(
                    _type='list',
                    assign=deque([
                        AddOp(
                            left=Name(
                                identifier='elem'
                            ),
                            right=Name(
                                identifier='b',
                                value=6
                            )
                        )
                    ]),
                    comprehensions=deque([
                        Comprehension(
                            assigns=deque([
                                Name(
                                    identifier='elem'
                                )
                            ]),
                            iterator=deque([
                                Name(
                                    identifier='a',
                                    value=[
                                        0,
                                        1,
                                        2,
                                        3,
                                        4,
                                        5
                                    ]
                                )
                            ]),
                            _is_async=False
                        )
                    ])
                )
            ])
        )
    ])

# # TESTS: Comments, Inline comments, comment commands
# # TODO: Implement inline comment commands? Possible? Easy?


def test_elif_block():
    ib = IfBlock(
            test=deque([Constant(2), "<=", Name("a"), "<", Constant(5)]),
            orelse=deque([
                IfBlock(
                    test=deque([Name("a"), ">", Name("b")]),
                    orelse=deque([
                        CalcLine(
                            assigns=deque([Name("d")]),
                            expression_tree=deque([Constant(6)]),
                        ),
                        ExprLine(
                            expression_tree=deque([
                                FunctionCall(
                                    namespace=deque(["__main__"]),
                                    function_name=deque(["print"]),
                                    args=deque([Name("d")]),
                                ),
                            ])
                        ),
                    ]),
                    lines=deque([
                        CalcLine(
                            assigns=deque([Name("d")]),
                            expression_tree=deque([Constant(5)])
                        ),
                        ExprLine(
                            expression_tree=deque([
                                FunctionCall(
                                    namespace=deque(["__main__"]),
                                    function_name=deque(["print"]),
                                    args=deque([Name("d")]),
                                )
                            ])
                        )
                    ])
                )
            ]),
            lines=deque([
                CalcLine(
                    assigns=deque([Name("d")]),
                    expression_tree=deque([Constant(4)])
                ),
                ExprLine(
                    expression_tree=deque([
                        FunctionCall(
                            namespace=deque(["__main__"]),
                            function_name=deque(["print"]),
                            args=deque([Name("d")]),
                        )
                    ])
                )
            ]),
        )
    assert ElifBlock.from_if_tree(ib) == ElifBlock(
        lines=deque([
            IfBlock(
                lines=deque([
                    CalcLine(
                        assigns=deque([
                            Name(
                                identifier='d'
                            )
                        ]),
                        expression_tree=deque([
                            Constant(
                                value=4
                            )
                        ])
                    ),
                    ExprLine(
                        expression_tree=deque([
                            FunctionCall(
                                namespace=deque([
                                    '__main__'
                                ]),
                                function_name=deque([
                                    'print'
                                ]),
                                args=deque([
                                    Name(
                                        identifier='d'
                                    )
                                ])
                            )
                        ])
                    )
                ]),
                test=deque([
                    Constant(
                        value=2
                    ),
                    '<=',
                    Name(
                        identifier='a'
                    ),
                    '<',
                    Constant(
                        value=5
                    )
                ]),
                orelse=deque([
                    IfBlock(
                        lines=deque([
                            CalcLine(
                                assigns=deque([
                                    Name(
                                        identifier='d'
                                    )
                                ]),
                                expression_tree=deque([
                                    Constant(
                                        value=5
                                    )
                                ])
                            ),
                            ExprLine(
                                expression_tree=deque([
                                    FunctionCall(
                                        namespace=deque([
                                            '__main__'
                                        ]),
                                        function_name=deque([
                                            'print'
                                        ]),
                                        args=deque([
                                            Name(
                                                identifier='d'
                                            )
                                        ])
                                    )
                                ])
                            )
                        ]),
                        test=deque([
                            Name(
                                identifier='a'
                            ),
                            '>',
                            Name(
                                identifier='b'
                            )
                        ]),
                        orelse=deque([
                            CalcLine(
                                assigns=deque([
                                    Name(
                                        identifier='d'
                                    )
                                ]),
                                expression_tree=deque([
                                    Constant(
                                        value=6
                                    )
                                ])
                            ),
                            ExprLine(
                                expression_tree=deque([
                                    FunctionCall(
                                        namespace=deque([
                                            '__main__'
                                        ]),
                                        function_name=deque([
                                            'print'
                                        ]),
                                        args=deque([
                                            Name(
                                                identifier='d'
                                            )
                                        ])
                                    )
                                ])
                            )
                        ])
                    )
                ])
            ),
            IfBlock(
                lines=deque([
                    CalcLine(
                        assigns=deque([
                            Name(
                                identifier='d'
                            )
                        ]),
                        expression_tree=deque([
                            Constant(
                                value=5
                            )
                        ])
                    ),
                    ExprLine(
                        expression_tree=deque([
                            FunctionCall(
                                namespace=deque([
                                    '__main__'
                                ]),
                                function_name=deque([
                                    'print'
                                ]),
                                args=deque([
                                    Name(
                                        identifier='d'
                                    )
                                ])
                            )
                        ])
                    )
                ]),
                test=deque([
                    Name(
                        identifier='a'
                    ),
                    '>',
                    Name(
                        identifier='b'
                    )
                ]),
                orelse=deque([
                    CalcLine(
                        assigns=deque([
                            Name(
                                identifier='d'
                            )
                        ]),
                        expression_tree=deque([
                            Constant(
                                value=6
                            )
                        ])
                    ),
                    ExprLine(
                        expression_tree=deque([
                            FunctionCall(
                                namespace=deque([
                                    '__main__'
                                ]),
                                function_name=deque([
                                    'print'
                                ]),
                                args=deque([
                                    Name(
                                        identifier='d'
                                    )
                                ])
                            )
                        ])
                    )
                ])
            )
        ])
    )


def test_hcsequence():
    source_1 = """
a = 4
b = 5
if 2 <= a < 5:
    d = 4
    if d == 3:
        print(d)
    elif d == 5:
        print(d)
    elif d == 4:
        print(d)
    else:
        print("TWELVE")
    print(d)
elif a > b:
    d = 5
    print(d)
else:
    d = 6
    print(d)
"""
    seq = HcSequence.from_source(source_1, {"a": 4, "b": 5, "d": 4}, {})
    assert seq.sequence == deque([
            CalcLine(
                assigns=deque([
                    Name(
                        identifier='a',
                        value=4
                    )
                ]),
                expression_tree=deque([
                    Constant(
                        value=4
                    )
                ])
            ),
            CalcLine(
                assigns=deque([
                    Name(
                        identifier='b',
                        value=5
                    )
                ]),
                expression_tree=deque([
                    Constant(
                        value=5
                    )
                ])
            ),
            ElifBlock(
                lines=deque([
                    IfBlock(
                        lines=deque([
                            CalcLine(
                                level=1,
                                assigns=deque([
                                    Name(
                                        identifier='d',
                                        value=4
                                    )
                                ]),
                                expression_tree=deque([
                                    Constant(
                                        value=4
                                    )
                                ])
                            ),
                            ElifBlock(
                                level=1,
                                lines=deque([
                                    IfBlock(
                                        level=1,
                                        lines=deque([
                                            ExprLine(
                                                level=2,
                                                expression_tree=deque([
                                                    FunctionCall(
                                                        namespace=Name(
                                                            identifier='__main__',
                                                            value='__main__'
                                                        ),
                                                        function_name=Name(
                                                            identifier='print',
                                                            value='print'
                                                        ),
                                                        args=deque([
                                                            Name(
                                                                identifier='d',
                                                                value=4
                                                            )
                                                        ])
                                                    )
                                                ])
                                            )
                                        ]),
                                        test=Compare(
                                            comparison=deque([
                                                Name(
                                                    identifier='d',
                                                    value=4
                                                ),
                                                EqOp,
                                                Constant(
                                                    value=3
                                                )
                                            ])
                                        ),
                                        orelse=deque([
                                            IfBlock(
                                                level=1,
                                                lines=deque([
                                                    ExprLine(
                                                        level=2,
                                                        expression_tree=deque([
                                                            FunctionCall(
                                                                namespace=Name(
                                                                    identifier='__main__',
                                                                    value='__main__'
                                                                ),
                                                                function_name=Name(
                                                                    identifier='print',
                                                                    value='print'
                                                                ),
                                                                args=deque([
                                                                    Name(
                                                                        identifier='d',
                                                                        value=4
                                                                    )
                                                                ])
                                                            )
                                                        ])
                                                    )
                                                ]),
                                                test=Compare(
                                                    comparison=deque([
                                                        Name(
                                                            identifier='d',
                                                            value=4
                                                        ),
                                                        EqOp,
                                                        Constant(
                                                            value=5
                                                        )
                                                    ])
                                                ),
                                                orelse=deque([
                                                    IfBlock(
                                                        level=1,
                                                        lines=deque([
                                                            ExprLine(
                                                                level=2,
                                                                expression_tree=deque([
                                                                    FunctionCall(
                                                                        namespace=Name(
                                                                            identifier='__main__',
                                                                            value='__main__'
                                                                        ),
                                                                        function_name=Name(
                                                                            identifier='print',
                                                                            value='print'
                                                                        ),
                                                                        args=deque([
                                                                            Name(
                                                                                identifier='d',
                                                                                value=4
                                                                            )
                                                                        ])
                                                                    )
                                                                ])
                                                            )
                                                        ]),
                                                        test=Compare(
                                                            comparison=deque([
                                                                Name(
                                                                    identifier='d',
                                                                    value=4
                                                                ),
                                                                EqOp,
                                                                Constant(
                                                                    value=4
                                                                )
                                                            ])
                                                        ),
                                                        orelse=deque([
                                                            ExprLine(
                                                                expression_tree=deque([
                                                                    FunctionCall(
                                                                        namespace=Name(
                                                                            identifier='__main__',
                                                                            value='__main__'
                                                                        ),
                                                                        function_name=Name(
                                                                            identifier='print',
                                                                            value='print'
                                                                        ),
                                                                        args=deque([
                                                                            Constant(
                                                                                value='TWELVE'
                                                                            )
                                                                        ])
                                                                    )
                                                                ])
                                                            )
                                                        ]),
                                                        is_true=True
                                                    )
                                                ]),
                                                is_true=False
                                            )
                                        ]),
                                        is_true=False
                                    ),
                                    IfBlock(
                                        level=1,
                                        lines=deque([
                                            ExprLine(
                                                level=2,
                                                expression_tree=deque([
                                                    FunctionCall(
                                                        namespace=Name(
                                                            identifier='__main__',
                                                            value='__main__'
                                                        ),
                                                        function_name=Name(
                                                            identifier='print',
                                                            value='print'
                                                        ),
                                                        args=deque([
                                                            Name(
                                                                identifier='d',
                                                                value=4
                                                            )
                                                        ])
                                                    )
                                                ])
                                            )
                                        ]),
                                        test=Compare(
                                            comparison=deque([
                                                Name(
                                                    identifier='d',
                                                    value=4
                                                ),
                                                EqOp,
                                                Constant(
                                                    value=5
                                                )
                                            ])
                                        ),
                                        orelse=deque([
                                            IfBlock(
                                                level=1,
                                                lines=deque([
                                                    ExprLine(
                                                        level=2,
                                                        expression_tree=deque([
                                                            FunctionCall(
                                                                namespace=Name(
                                                                    identifier='__main__',
                                                                    value='__main__'
                                                                ),
                                                                function_name=Name(
                                                                    identifier='print',
                                                                    value='print'
                                                                ),
                                                                args=deque([
                                                                    Name(
                                                                        identifier='d',
                                                                        value=4
                                                                    )
                                                                ])
                                                            )
                                                        ])
                                                    )
                                                ]),
                                                test=Compare(
                                                    comparison=deque([
                                                        Name(
                                                            identifier='d',
                                                            value=4
                                                        ),
                                                        EqOp,
                                                        Constant(
                                                            value=4
                                                        )
                                                    ])
                                                ),
                                                orelse=deque([
                                                    ExprLine(
                                                        expression_tree=deque([
                                                            FunctionCall(
                                                                namespace=Name(
                                                                    identifier='__main__',
                                                                    value='__main__'
                                                                ),
                                                                function_name=Name(
                                                                    identifier='print',
                                                                    value='print'
                                                                ),
                                                                args=deque([
                                                                    Constant(
                                                                        value='TWELVE'
                                                                    )
                                                                ])
                                                            )
                                                        ])
                                                    )
                                                ]),
                                                is_true=True
                                            )
                                        ]),
                                        is_true=False
                                    ),
                                    IfBlock(
                                        level=1,
                                        lines=deque([
                                            ExprLine(
                                                level=2,
                                                expression_tree=deque([
                                                    FunctionCall(
                                                        namespace=Name(
                                                            identifier='__main__',
                                                            value='__main__'
                                                        ),
                                                        function_name=Name(
                                                            identifier='print',
                                                            value='print'
                                                        ),
                                                        args=deque([
                                                            Name(
                                                                identifier='d',
                                                                value=4
                                                            )
                                                        ])
                                                    )
                                                ])
                                            )
                                        ]),
                                        test=Compare(
                                            comparison=deque([
                                                Name(
                                                    identifier='d',
                                                    value=4
                                                ),
                                                EqOp,
                                                Constant(
                                                    value=4
                                                )
                                            ])
                                        ),
                                        orelse=deque([
                                            ExprLine(
                                                expression_tree=deque([
                                                    FunctionCall(
                                                        namespace=Name(
                                                            identifier='__main__',
                                                            value='__main__'
                                                        ),
                                                        function_name=Name(
                                                            identifier='print',
                                                            value='print'
                                                        ),
                                                        args=deque([
                                                            Constant(
                                                                value='TWELVE'
                                                            )
                                                        ])
                                                    )
                                                ])
                                            )
                                        ]),
                                        is_true=True
                                    ),
                                    ElseBlock(
                                        level=1
                                    )
                                ])
                            ),
                            ExprLine(
                                level=1,
                                expression_tree=deque([
                                    FunctionCall(
                                        namespace=Name(
                                            identifier='__main__',
                                            value='__main__'
                                        ),
                                        function_name=Name(
                                            identifier='print',
                                            value='print'
                                        ),
                                        args=deque([
                                            Name(
                                                identifier='d',
                                                value=4
                                            )
                                        ])
                                    )
                                ])
                            )
                        ]),
                        test=Compare(
                            comparison=deque([
                                Constant(
                                    value=2
                                ),
                                LtEOp,
                                Name(
                                    identifier='a',
                                    value=4
                                ),
                                LtOp,
                                Constant(
                                    value=5
                                )
                            ])
                        ),
                        orelse=deque([
                            IfBlock(
                                lines=deque([
                                    CalcLine(
                                        level=1,
                                        assigns=deque([
                                            Name(
                                                identifier='d',
                                                value=4
                                            )
                                        ]),
                                        expression_tree=deque([
                                            Constant(
                                                value=5
                                            )
                                        ])
                                    ),
                                    ExprLine(
                                        level=1,
                                        expression_tree=deque([
                                            FunctionCall(
                                                namespace=Name(
                                                    identifier='__main__',
                                                    value='__main__'
                                                ),
                                                function_name=Name(
                                                    identifier='print',
                                                    value='print'
                                                ),
                                                args=deque([
                                                    Name(
                                                        identifier='d',
                                                        value=4
                                                    )
                                                ])
                                            )
                                        ])
                                    )
                                ]),
                                test=Compare(
                                    comparison=deque([
                                        Name(
                                            identifier='a',
                                            value=4
                                        ),
                                        GtOp,
                                        Name(
                                            identifier='b',
                                            value=5
                                        )
                                    ])
                                ),
                                orelse=deque([
                                    CalcLine(
                                        assigns=deque([
                                            Name(
                                                identifier='d',
                                                value=4
                                            )
                                        ]),
                                        expression_tree=deque([
                                            Constant(
                                                value=6
                                            )
                                        ])
                                    ),
                                    ExprLine(
                                        expression_tree=deque([
                                            FunctionCall(
                                                namespace=Name(
                                                    identifier='__main__',
                                                    value='__main__'
                                                ),
                                                function_name=Name(
                                                    identifier='print',
                                                    value='print'
                                                ),
                                                args=deque([
                                                    Name(
                                                        identifier='d',
                                                        value=4
                                                    )
                                                ])
                                            )
                                        ])
                                    )
                                ]),
                                is_true=False
                            )
                        ]),
                        is_true=True
                    ),
                    IfBlock(
                        lines=deque([
                            CalcLine(
                                level=1,
                                assigns=deque([
                                    Name(
                                        identifier='d',
                                        value=4
                                    )
                                ]),
                                expression_tree=deque([
                                    Constant(
                                        value=5
                                    )
                                ])
                            ),
                            ExprLine(
                                level=1,
                                expression_tree=deque([
                                    FunctionCall(
                                        namespace=Name(
                                            identifier='__main__',
                                            value='__main__'
                                        ),
                                        function_name=Name(
                                            identifier='print',
                                            value='print'
                                        ),
                                        args=deque([
                                            Name(
                                                identifier='d',
                                                value=4
                                            )
                                        ])
                                    )
                                ])
                            )
                        ]),
                        test=Compare(
                            comparison=deque([
                                Name(
                                    identifier='a',
                                    value=4
                                ),
                                GtOp,
                                Name(
                                    identifier='b',
                                    value=5
                                )
                            ])
                        ),
                        orelse=deque([
                            CalcLine(
                                assigns=deque([
                                    Name(
                                        identifier='d',
                                        value=4
                                    )
                                ]),
                                expression_tree=deque([
                                    Constant(
                                        value=6
                                    )
                                ])
                            ),
                            ExprLine(
                                expression_tree=deque([
                                    FunctionCall(
                                        namespace=Name(
                                            identifier='__main__',
                                            value='__main__'
                                        ),
                                        function_name=Name(
                                            identifier='print',
                                            value='print'
                                        ),
                                        args=deque([
                                            Name(
                                                identifier='d',
                                                value=4
                                            )
                                        ])
                                    )
                                ])
                            )
                        ]),
                        is_true=False
                    )
                ])
            )
        ])
    assert seq.hc_globals == {"a": 4, "b": 5, "d": 4}
    assert seq.hc_locals == {}
