GREEK_LOWER = {
    "alpha": "\\alpha",
    "beta": "\\beta",
    "gamma": "\\gamma",
    "delta": "\\delta",
    "epsilon": "\\epsilon",
    "zeta": "\\zeta",
    "theta": "\\theta",
    "iota": "\\iota",
    "kappa": "\\kappa",
    "mu": "\\mu",
    "nu": "\\nu",
    "xi": "\\xi",
    "omicron": "\\omicron",
    "pi": "\\pi",
    "rho": "\\rho",
    "sigma": "\\sigma",
    "tau": "\\tau",
    "upsilon": "\\upsilon",
    "phi": "\\phi",
    "chi": "\\chi",
    "omega": "\\omega",
    "eta": "\\eta",
    "psi": "\\psi",
    "lamb": "\\lambda",
}

GREEK_UPPER = {
    "Alpha": "\\Alpha",
    "Beta": "\\Beta",
    "Gamma": "\\Gamma",
    "Delta": "\\Delta",
    "Epsilon": "\\Epsilon",
    "Zeta": "\\Zeta",
    "Theta": "\\Theta",
    "Iota": "\\Iota",
    "Kappa": "\\Kappa",
    "Mu": "\\Mu",
    "Nu": "\\Nu",
    "Xi": "\\Xi",
    "Omicron": "\\Omicron",
    "Pi": "\\Pi",
    "Rho": "\\Rho",
    "Sigma": "\\Sigma",
    "Tau": "\\Tau",
    "Upsilon": "\\Upsilon",
    "Phi": "\\Phi",
    "Chi": "\\Chi",
    "Omega": "\\Omega",
    "Eta": "\\Eta",
    "Psi": "\\Psi",
    "Lamb": "\\Lambda",
}